#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-py4j
Version  : 0.10.7
Release  : 2
URL      : https://repo1.maven.org/maven2/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.jar
Source0  : https://repo1.maven.org/maven2/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.jar
Source1  : https://repo1.maven.org/maven2/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-py4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-py4j package.
Group: Data

%description data
data components for the mvn-py4j package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.jar
/usr/share/java/.m2/repository/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.pom
